name: Build, Test and Publish
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        registry-url: 'https://npm.pkg.github.com'
    - run: sed -i 's/GITHUB_REGISTRY_TOKEN/GH_TOKEN/' .npmrc
    - run: npm install
    - run: npm run build
    - run: yarn publish --verbose
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
